### ISSUE TITLE
Error Message : "- The command " <unknown> " is not currently available"

### ISSUE THREAD

**Issue by ruihildt** [romashamin/Size-Marks-PS#22]
What's happening : Every time I use the script, the following error appears. (Tested on a blank file)
![screenshot_4](https://cloud.githubusercontent.com/assets/13787166/9300679/eaf8470e-44c8-11e5-830c-73094c498605.png)

The script still works perfectly, I can close the error message and continue working.

Adobe Photoshop Version: 2014.0.0 20140508.r.58 2014/05/08:23:59:59  x64
Operating System: Windows 8.1 64-bit

**Comment by romashamin** [comment]
@ruihildt thanks for the report!

I guess that is happening because PS CC 2014 does not have artboards. Try to install [Size Marks 1.0](https://github.com/romashamin/Size-Marks-PS/releases/tag/v1.0) *(this version does not contain any artboard features)* and let me know whether or not the error appears.

**Comment by ruihildt** [comment]
The error doesn't appear with Size Marks 1.0.

**Comment by romashamin** [comment]
@ruihildt 👍
